create table operations (
                            id bigint primary key not null generated by default as identity,
                            amount float not null default 0,
                            type varchar not null,
                            time timestamp not null,
                            user_id bigint not null,
                            foreign key (user_id) references users(id)
);

create table users(
                      id bigint primary key not null  generated by default as identity,
                      balance float not null default 0,
                      check ( balance >= 0 )
);